name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Посмотрим, где лежат apk, чтобы убедиться
      - name: List APK files
        run: |
          echo "Searching for APKs..."
          find . -type f -name "*.apk" -print

      - name: Upload APKs
        uses: actions/upload-artifact@v4   # <-- обновили на v4
        with:
          name: app-apk
          path: |
            **/*.apk
          if-no-files-found: error
